### PR TITLE
Add CentOS Stream as a source

### PR DESCRIPTION
**Pull request by mmathesius**
Work in progress. Still need to look into what changes may be needed for fetching content resolver data.

### CODE REVIEW

**Comment by tdawson** [comment]
That looks very good.
Would you be able/willing to have f34 as well as rawhide?

**Comment by mmathesius** [comment]
> Would you be able/willing to have f34 as well as rawhide?

Yup. Working on it.

**Review by tdawson — APPROVED** [review]
Looks good.  Passes my tests.  Fixes things I had on my list to fix.
Approve

**Comment by mmathesius** [comment]
Feel free to merge this if you like. I'll add the F34 work as a separate PR.

**Pull request merged**
